config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :users
  resources :products, :images


  get 'welcome/index'
  root 'welcome#index'
  get 'sign_out', to: 'devise#sign_out'

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :product
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :image
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end
  def show
    @image = Image.find(params[:id])
  end

  def create
    #get image url
    @file_url = params['image']['file_object'].original_filename
    directory = 'app/assets/images/'
    path = File.join(directory, @file_url)
    # Write image File out
    File.open(path, 'wb') { |f| f.write(params['image']['file_object'].read) }

    # save image to db
    @new_image=Image.new(url: @file_url,title: params['image']['title'], alt:params['image']['alt'])
    @new_image.save
    redirect_to @new_image
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_admin!
	skip_before_action :authenticate_admin!, only:[:index,:show]
	def index
		@products = Product.all
	end
	def new
		@product = Product.new
	end
	def create
		@product = Product.new(params.require(:product).permit(:cost,:name,:price,:image_id,:qty,:restock_time,:description))
		@product.save
		redirect_to @product
	end
	def show
		@product = Product.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/index.html.erb
<h1>Images</h1>

app/views/images/new.html.erb
<div class="new-image-view row col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
  <div class="row">
    <div class="col-6">
      <h1>New Image</h1>
      <%= form_for @image, url: images_path do |i| %>
          <div class=".form-group">
            <%= i.label :title %>
            <%= i.text_field :title ,class:'form-control'%>
          </div>
          <div class=".form-group">
            <%= i.label 'File' %>
            <%= i.file_field :file_object %>
          </div>
          <div class=".form-group">
            <%= i.label :alt %>
            <%= i.text_field :alt ,class:'form-control'%>
          </div>
          <div class=".form-group">
            <%= i.label :width %>
              <%= number_field(:image ,:width, step:1,class:'form-control') %>
          </div>
          <div class=".form-group">
            <%= i.label :height %>
            <%= number_field(:image ,:height, step:1,class:'form-control') %>
          </div>
          <%= i.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/images/show.erb
<div class="mirrawe-single-image-view">
  <p>
    <strong>Title</strong>
    <%= @image.title %>

  <p>
    <%= image_tag(@image.url, {alt: @image.alt, size: "250x250"}) %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MirraweWebshop</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic|Open+Sans:400,600,700|Alice' %>

</head>
<body>
<%= render 'shared/navBar' %>
<div id="railsMainContent" class="container-fluid">
  <%= yield %>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#railsMainContent').height(window.innerHeight - $('#header').height());
    });
    $(window).resize(function () {
        $('#railsMainContent').height(window.innerHeight - $('#header').height());
    });
</script>
<div class="server-message-holder">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>
</body>
</html>

app/views/products/index.html.erb
<% if admin_signed_in? %>
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="adminDropdown" data-toggle="dropdown" aria-expanded="true">
        Admin <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="adminDropdown">
        <li><%= link_to "Add Image", '/images/new' %></li>
        <li><%= link_to "Add Product", '/products/new' %></li>
        <li><%= link_to "Logout Admin Privileges", '/admins/sign_out', method: 'DELETE' %></li>
      </ul>
    </div>
<% end %>
<%= render 'shared/page_banner', :page_title => 'Products' %>
<div class="product-index">
  <ul id="product_list">
    <% for @product in @products %>
        <li class="product-item-wrapper">
          <div class="product-item">
            <div class="product-image-wrapper">
              <div class="product-image" style='background-image:url(<%= path_to_image(@product.image.url) %>);'></div>
              <div class="product-image-back">
                <div class="product-image-back-blur">
                  <%= @product.description %>
                </div>
              </div>
            </div>
            <div class="product-item-title">
              <%= link_to "View", @product %>
            </div>
            <div class="product-price">
              $ <%= @product.price %>.00
            </div>
            <div class="product-buttons">
              <button class="shop-function-button buy">
                <i class="glyphicon glyphicon-shopping-cart "></i>
              </button>
              <button class="shop-function-button remove" onclick="window.location.href='#'">
                <i class="glyphicon glyphicon-heart "></i>
              </button>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
</div>

app/views/products/new.html.erb
<div class="new-product-view row col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
  <h1>New Product</h1>
  <%= form_for @product do |p| %>
      <div class="form-group">
        <%= p.label :name, class:'tert' %>
        <%= p.text_field :name, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= p.label :cost, class:'tert' %>
        <%= number_field :product,:cost,class:'form-control' %>
      </div>
      <div class="form-group">
        <%= p.label :price, class:'tert' %>
        <%= number_field :product,:price,class:'form-control' %>
      </div>
      <div class="form-group">
        <%= p.label :image, class:'tert' %>
        <%= p.collection_select(  :image_id , Image.all , :id , :title )%>
      </div>
      <div class="form-group">
        <%= p.label :qty, class:'tert' %>
        <%= number_field :product,:qty,class:'form-control' %>
      </div>
      <div class="form-group">
        <%= p.label :restock_time, class:'tert' %>
        <%= number_field :product,:restock_time,class:'form-control' %>
      </div>
      <div class="form-group">
        <%= p.label :description, class:'tert' %>
        <%= p.text_field :description, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= p.submit %>
      </div>
  <% end %>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p>Cost :$<%= @product.cost %></p>

app/views/shared/_navBar.html.erb
<div id="header">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand col-lg-offset-1">
          <%= image_tag "Mirrawe.svg",size: '48x48',class: 'mw-inline' %>
          <%= link_to "mirrawe" ,'/',class: 'mw-inline golden' %>
        </div>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="mw-indent-right"><%= link_to "Home",'/' ,class:'hidden-sm hidden-md'%></li>
          <li class="mw-indent-right"><%= link_to "Products",'/products' %></li>
          <li class="mw-indent-right"><%= link_to "Wishlist",'/images',class:'hidden-sm hidden-md' %></li>
          <li class="mw-indent-right"><%= link_to "Account",'/users/edit' %></li>
          <li class="mw-indent-right"><%= link_to "Cart",'/images' %></li>
          <li class="mw-indent-right"><%= link_to "Contact",'/images',class:'hidden-sm hidden-md' %></li>
          <li class="spacer"> <div class="spacer hidden-sm hidden-md"></div></li>



        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
</div>

app/views/shared/_page_banner.html.erb
<div class="page-banner">
  <h1><%= page_title %></h1>
  <div class="underneath-title-padding"></div>
  <div class="page-banner-details"></div>
  <div class="page-banner-after-padding"></div>
</div>

app/views/welcome/index.html.erb
<div id="welcome-view" style="background-image: url(<%= image_path "background.jpg" %>)">
  <div class="v-spacer-medium hidden-xs"></div>
  <div class="v-spacer-medium hidden-xs"></div>
  <div class="v-spacer-medium hidden-xs"></div>
  <div class="content-wrapper">
    <div class="homepage-content">
      <div class="center-text">
        <h1 class="massive-text">A cut above the rest</h1>
        <div class="v-spacer-medium"></div>
        <div class="curly"><h2>A webshop apart</h2></div>
        <div class="v-spacer-medium"></div>
        <div class="homepage_links">
          <div class="left"><%= button_to "Get Started!", '/', class: 'homepage_button',method: :get %></div>
          <div><%= button_to "Browse Store", '/products', class: 'homepage_button',method: :get %></div>
        </div>
      </div>
    </div>
  </div>

</div>